application: mtgcubelogin
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.application

- url: /logout
  script: main.application

- url: /sign
  script: main.application

- url: /css
  static_dir: css

- url: /font-awesome-4.1.0
  static_dir: font-awesome-4.1.0

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /less
  static_dir: less

- url: /mail
  static_dir: mail

- url: /gae-sessions-master
  static_dir: gae-sessions-master